version: "3.9"
services:
  database:
    image: postgres
    container_name: postgres_database
    restart: always
    ports:
      - "12666:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: time_management
  app:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - "3100:3100"
    depends_on:
      - database
    environment:
        DATABASE_URL: postgres://postgres:postgres_password@database:5432/time_management
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
